// <auto-generated />
using System;
using Infraestructura.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    [Migration("20251124230230_init1232")]
    partial class init1232
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("UserId");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", (string)null);

                    b.HasDiscriminator<string>("PaymentType").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.RecurringPayment", b =>
                {
                    b.HasBaseType("LibreriaLogicaNegocio.Entities.Payment");

                    b.HasDiscriminator().HasValue("Recurring");
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.UniquePayment", b =>
                {
                    b.HasBaseType("LibreriaLogicaNegocio.Entities.Payment");

                    b.HasDiscriminator().HasValue("Unique");
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Administrator", b =>
                {
                    b.HasBaseType("LibreriaLogicaNegocio.Entities.User");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Employee", b =>
                {
                    b.HasBaseType("LibreriaLogicaNegocio.Entities.User");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Manager", b =>
                {
                    b.HasBaseType("LibreriaLogicaNegocio.Entities.User");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Expense", b =>
                {
                    b.OwnsOne("LibreriaLogicaNegocio.Vo.Description", "Description", b1 =>
                        {
                            b1.Property<int>("ExpenseId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Description");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.Name", "Name", b1 =>
                        {
                            b1.Property<int>("ExpenseId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Log", b =>
                {
                    b.HasOne("LibreriaLogicaNegocio.Entities.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibreriaLogicaNegocio.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Payment", b =>
                {
                    b.HasOne("LibreriaLogicaNegocio.Entities.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibreriaLogicaNegocio.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.Description", "Description", b1 =>
                        {
                            b1.Property<int>("PaymentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.Amount", "Amount", b1 =>
                        {
                            b1.Property<int>("PaymentId")
                                .HasColumnType("int");

                            b1.Property<double>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("float")
                                .HasColumnName("Amount");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.PaymentMethod", "PaymentMethod", b1 =>
                        {
                            b1.Property<int>("PaymentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PaymentMethod");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("PaymentMethod")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.Team", b =>
                {
                    b.OwnsOne("LibreriaLogicaNegocio.Vo.Name", "Name", b1 =>
                        {
                            b1.Property<int>("TeamId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("TeamId");

                            b1.ToTable("Teams");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.User", b =>
                {
                    b.HasOne("LibreriaLogicaNegocio.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.Name", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.LastName", "LastName", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.RecurringPayment", b =>
                {
                    b.OwnsOne("LibreriaLogicaNegocio.Vo.DateFrom", "DateFrom", b1 =>
                        {
                            b1.Property<int>("RecurringPaymentId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateFrom");

                            b1.HasKey("RecurringPaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("RecurringPaymentId");
                        });

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.DateTill", "DateTill", b1 =>
                        {
                            b1.Property<int>("RecurringPaymentId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateTill");

                            b1.HasKey("RecurringPaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("RecurringPaymentId");
                        });

                    b.Navigation("DateFrom")
                        .IsRequired();

                    b.Navigation("DateTill")
                        .IsRequired();
                });

            modelBuilder.Entity("LibreriaLogicaNegocio.Entities.UniquePayment", b =>
                {
                    b.OwnsOne("LibreriaLogicaNegocio.Vo.BillNumber", "BillNumber", b1 =>
                        {
                            b1.Property<int>("UniquePaymentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BillNumber");

                            b1.HasKey("UniquePaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("UniquePaymentId");
                        });

                    b.OwnsOne("LibreriaLogicaNegocio.Vo.PayDate", "PayDate", b1 =>
                        {
                            b1.Property<int>("UniquePaymentId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("PayDate");

                            b1.HasKey("UniquePaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("UniquePaymentId");
                        });

                    b.Navigation("BillNumber")
                        .IsRequired();

                    b.Navigation("PayDate")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
